### ISSUE TITLE
Viewer ignores aliases

### ISSUE THREAD

**Issue by sheumais** [JannisX11/molang-grapher#2]
According to [the documentation](https://bedrock.dev/docs/stable/Molang#Aliases), this expression `math.cos(q.anim_time*360)*10` should work perfectly fine and display a cosine wave. Unfortunately, in the current state of the grapher, the `q.anim_time` is ignored completely and it is treated as `math.cos(360)*10` which is just a straight line. Using `q.anim_time` rather than `query.anim_time` works perfectly fine within the Blockbench program, so it seems fitting that the grapher should reflect that and show the proper graph.

**Comment by Sheumais** [comment]
Fix:
Replace lines 26-33:
`const X_variables = [
	'query.anim_time',
	'query.life_time',
	'time',
	'query.modified_distance_moved',
	'variable.particle_age',
	'variable.emitter_age'
]`

With updated code:
`const X_variables = [
	'query.anim_time',
	'query.life_time',
	'time',
	'query.modified_distance_moved',
	'variable.particle_age',
	'variable.emitter_age',
	'q.anim_time',
	'q.life_time',
	'q.modified_distance_moved',
	'v.particle_age',
	'v.emitter_age'
]`

in [this](https://github.com/JannisX11/molang-grapher/blob/main/src/components/Graph.vue) file.
